version: "3.1"

services:
  # FastAPI App
  fastapi:
    build: ./fastapi
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8305"]
    depends_on:
      - mongo
    volumes:
      - ./fastapi:/fastapi  # Maps the current directory to /app inside the container
    ports:
      - "8305:8305"
    networks:
      - pm-networks
    environment:
      TZ: "Asia/Bangkok"
    env_file:
      - .env

  # Mongo Image
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - pm-networks
    environment:
      TZ: "Asia/Bangkok"
    env_file:
      - .env

  # Mongo Express
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pm-networks
    environment:
      TZ: "Asia/Bangkok"
    env_file:
      - .env

networks:
  pm-networks:
    driver: bridge
    