version: "3.1"

services:
  # FastAPI App
  fastapi:
    build: ./fastapi_app
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8305"]
    depends_on:
      - mongo
    volumes:
      - ./fastapi_app:/fastapi_app  # Maps the current directory to /app inside the container
    ports:
      - "8305:8305"
    networks:
      - pm-networks
    environment:
      TZ: "Asia/Bangkok"
    env_file:
      - .env

  # Mongo Image
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - pm-networks
    environment:
      - MONGO_INITDB_ROOT_USERNAME = ${USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD = ${PASSWORD}
      - TZ = Asia/Bangkok

  # Mongo Express
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pm-networks
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME = ${USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD = ${PASSWORD}
      - ME_CONFIG_MONGODB_URL = ${DB_ADDRESS}
      - ME_CONFIG_BASICAUTH = false
      - TZ = Asia/Bangkok

networks:
  pm-networks:
    driver: bridge
    
